apiVersion: v1
kind: Service
metadata:
  name: demo-app-spring
  labels:
    app: demo-app-spring
spec:
  type: LoadBalancer
  selector:
    app: demo-app-spring
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30002